apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: product-app
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service.product-app.svc.cluster.local:3306/productdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect